language: go
go:
  - master
os:
  - linux
  - osx
dist: trusty
sudo: false
install: true
script:
  - env GO111MODULE=on make restore
  - env GO111MODULE=on make build
  - env GO111MODULE=on make test
